language: objective-c
xcode_project: ArtikCloudTests/ArtikCloudClient.xcodeproj # path to your xcodeproj folder
xcode_scheme: ArtikCloudClientTests

script:
  - xcodebuild xcode_project CODE_SIGNING_REQUIRED=NO
